version: "3.0"
services:
  registry-backend:
    image: registry
    container_name: backend-registry
    ports:
      - "5001:5000"
    
    volumes:
      - type: volume
        source: my-registry
        target: /var/lib/registry
    networks:
      registry-network:
    restart: unless-stopped
    
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2 
    container_name: frontend-registry
    depends_on: 
      - registry-backend
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry-backend
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "8081:80"
    networks:
      registry-network:
    restart: unless-stopped
  
volumes:
  my-registry:
    #name: Image-Registry
  
networks:
  registry-network:
    driver: bridge
    #name: registry-network